version: '3.8'

services:
  facial:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: $USERNAME
        USERID: $USERID
    container_name: facial
    ports:
      - "5000:5000"
    networks:
      - facial-net
    volumes:
      - ./app:/app

networks:
  facial-net:
    driver: bridge
